import '../models/market.dart';
import '../models/product.dart';

const markets = <Market>[
  Market(
    id: 'ikas',
    name: 'Ikas Super Market',
    logoUrl: 'https://dummyimage.com/600x240/2e7d32/ffffff&text=IKAS',
  ),
  Market(
    id: 'dima',
    name: 'Dima Discount',
    logoUrl: 'https://dummyimage.com/600x240/1e4f9a/ffffff&text=DIMA',
  ),
  Market(
    id: 'macro',
    name: 'Macro',
    logoUrl: 'https://dummyimage.com/600x240/c55a1a/ffffff&text=MACRO',
  ),
  Market(
    id: 'kiler',
    name: 'Kiler',
    logoUrl: 'https://dummyimage.com/600x240/b71c1c/ffffff&text=KILER',
  ),
];

const demoProducts = <Product>[
  Product(
    id: 'banana',
    title: 'Banana',
    subtitle: 'Fresh',
    price: 2.00,
    imageUrl: 'assets/products/banana.jpg',
    category: 'Fruits',
  ),
  Product(
    id: 'typec',
    title: 'Type C charger',
    subtitle: 'Android Device',
    price: 12.00,
    imageUrl: 'assets/products/typec.png',
    category: 'Technology',
  ),
  Product(
    id: 'pomegranate',
    title: 'Pomegranate',
    subtitle: 'Fertilizer Free',
    price: 8.00,
    imageUrl: 'assets/products/pomegranate.jpg',
    category: 'Fruits',
  ),
  Product(
    id: 'apple',
    title: 'Red Apple',
    subtitle: 'Sweet & Crunchy',
    price: 3.00,
    imageUrl: 'assets/products/apple fruit.jpeg',
    category: 'Fruits',
  ),
  Product(
    id: 'orange',
    title: 'Orange',
    subtitle: 'Juicy',
    price: 2.50,
    imageUrl: 'assets/products/orange.jpeg',
    category: 'Fruits',
  ),
  Product(
    id: 'peach',
    title: 'Peach',
    subtitle: 'Sweet',
    price: 3.50,
    imageUrl: 'assets/products/fruits peach.jpeg',
    category: 'Fruits',
  ),
  Product(
    id: 'fruit_mix',
    title: 'Pear',
    subtitle: 'Deveci Pear',
    price: 5.00,
    imageUrl: 'assets/products/fruit2.jpeg',
    category: 'Fruits',
  ),
  Product(
    id: 'potato',
    title: 'Potatoes',
    subtitle: 'Fertilizer Free',
    price: 4.00,
    imageUrl: 'assets/products/potato.jpg',
    category: 'Vegetables',
  ),
  Product(
    id: 'parsley',
    title: 'Parsley',
    subtitle: 'Fresh',
    price: 3.00,
    imageUrl: 'assets/products/parsley.jpg',
    category: 'Vegetables',
  ),
  Product(
    id: 'tomato',
    title: 'Tomato',
    subtitle: 'Organic',
    price: 2.50,
    imageUrl: 'assets/products/vegetables1.jpeg',
    category: 'Vegetables',
  ),
  Product(
    id: 'axe',
    title: 'AXE',
    subtitle: 'Body Spray',
    price: 9.00,
    imageUrl: 'assets/products/axe.jpg',
    category: 'Popular',
  ),
  // Grocery Items (6 total)
// ... (skipping unchanged grocery/frozen/tech items to target the specific vegetable lines at the end of the file)
   
  // New Vegetables from assets
  Product(
    id: 'pepper',
    title: 'Eggplant',
    subtitle: 'Long Eggplant',
    price: 2.00,
    imageUrl: 'assets/products/vegetables2.jpeg',
    category: 'Vegetables',
  ),
  Product(
    id: 'cucumber',
    title: 'Pepper',
    subtitle: 'Charleston Pepper',
    price: 1.00,
    imageUrl: 'assets/products/vegetables3.jpeg',
    category: 'Vegetables',
  ),
  Product(
    id: 'onion',
    title: 'Mushroom',
    subtitle: 'Cultivated Mushroom',
    price: 2.00,
    imageUrl: 'assets/products/vegetables4.jpeg',
    category: 'Vegetables',
  ),
  // Grocery Items (6 total)
  Product(
    id: 'rice',
    title: 'Rice',
    subtitle: 'Osmancik 1kg',
    price: 15.00,
    imageUrl: 'assets/products/grocery1.jpeg',
    category: 'Grocery',
  ),
  Product(
    id: 'pasta',
    title: 'Pasta',
    subtitle: 'Italian Pasta 500g',
    price: 3.00,
    imageUrl: 'assets/products/grocery2.jpeg',
    category: 'Grocery',
  ),
  Product(
    id: 'flour',
    title: 'Flour',
    subtitle: 'Wheat Flour 1kg',
    price: 2.00,
    imageUrl: 'assets/products/grocery3.jpeg',
    category: 'Grocery',
  ),
  Product(
    id: 'milk_pack',
    title: 'Milk',
    subtitle: 'Full Fat 4x1L',
    price: 12.00,
    imageUrl: 'assets/products/grocery4.jpeg',
    category: 'Grocery',
  ),
  Product(
    id: 'oats',
    title: 'Oats',
    subtitle: 'Rolled Oats',
    price: 18.00,
    imageUrl: 'assets/products/grocery5.jpeg',
    category: 'Grocery',
  ),
  Product(
    id: 'sunflower_oil',
    title: 'Oil',
    subtitle: 'Sunflower Oil 1L',
    price: 6.00,
    imageUrl: 'assets/products/grocery6.jpeg',
    category: 'Grocery',
  ),
  // Frozen Items (6 total)
  Product(
    id: 'pizza',
    title: 'Margherita Pizza',
    subtitle: 'Italian Style',
    price: 9.00,
    imageUrl: 'assets/products/frozen pizza.jpg',
    category: 'Frozen',
  ),
  Product(
    id: 'icecream',
    title: 'Mixed Pizza',
    subtitle: 'Special Sauce',
    price: 6.00,
    imageUrl: 'assets/products/frozen1.jpeg',
    category: 'Frozen',
  ),
  Product(
    id: 'peas',
    title: 'Toast',
    subtitle: 'With Cheese',
    price: 4.00,
    imageUrl: 'assets/products/frozen2.jpeg',
    category: 'Frozen',
  ),
  Product(
    id: 'berries',
    title: 'Mixed Fruit',
    subtitle: 'Frozen Mix',
    price: 7.00,
    imageUrl: 'assets/products/frozen3.jpeg',
    category: 'Frozen',
  ),
  Product(
    id: 'nuggets',
    title: 'Spinach',
    subtitle: 'Cleaned 500g',
    price: 10.00,
    imageUrl: 'assets/products/frozen4.jpeg',
    category: 'Frozen',
  ),
  Product(
    id: 'fries',
    title: 'Fries',
    subtitle: 'Finger Fries',
    price: 5.00,
    imageUrl: 'assets/products/frozen5.jpeg',
    category: 'Frozen',
  ),
  // Technology Items
  Product(
    id: 'headphones',
    title: 'Headphones',
    subtitle: 'Wireless',
    price: 59.99,
    imageUrl: 'assets/products/technology1.jpeg',
    category: 'Technology',
  ),
  Product(
    id: 'smartwatch',
    title: 'Charger',
    subtitle: 'Fast Charger',
    price: 200.00,
    imageUrl: 'assets/products/technology2.jpeg',
    category: 'Technology',
  ),
  Product(
    id: 'powerbank',
    title: 'Plug Converter',
    subtitle: 'Universal Adapter',
    price: 25.00,
    imageUrl: 'assets/products/technology3.jpeg',
    category: 'Technology',
  ),
  Product(
    id: 'usb_cable',
    title: 'Powerbank',
    subtitle: 'Mini Powerbank',
    price: 9.00,
    imageUrl: 'assets/products/technology4.jpeg',
    category: 'Technology',
  ),
  Product(
    id: 'speaker',
    title: 'Wired Headphones',
    subtitle: 'Stereo Headphones',
    price: 35.00,
    imageUrl: 'assets/products/technology5.jpeg',
    category: 'Technology',
  ),
];
