// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-tta9nTFH-GETkPq-o7X3qI2FAZm1kTc',
    appId: '1:332873687212:web:4e22d1526ff574cc18bf09',
    messagingSenderId: '332873687212',
    projectId: 'apppro-55d82',
    authDomain: 'apppro-55d82.firebaseapp.com',
    storageBucket: 'apppro-55d82.firebasestorage.app',
    measurementId: 'G-P967PCF0MR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAGWRUa7l7Pl6jTGg2opTbuqMc1CkilLs',
    appId: '1:332873687212:android:74ff18c4e823bb7318bf09',
    messagingSenderId: '332873687212',
    projectId: 'apppro-55d82',
    storageBucket: 'apppro-55d82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2A_X7ImpotS_pxErjPiKeyAiagnE29lc',
    appId: '1:332873687212:ios:c06438b3b636ff0518bf09',
    messagingSenderId: '332873687212',
    projectId: 'apppro-55d82',
    storageBucket: 'apppro-55d82.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2A_X7ImpotS_pxErjPiKeyAiagnE29lc',
    appId: '1:332873687212:ios:c06438b3b636ff0518bf09',
    messagingSenderId: '332873687212',
    projectId: 'apppro-55d82',
    storageBucket: 'apppro-55d82.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-tta9nTFH-GETkPq-o7X3qI2FAZm1kTc',
    appId: '1:332873687212:web:e7cdf11d1f20a4c118bf09',
    messagingSenderId: '332873687212',
    projectId: 'apppro-55d82',
    authDomain: 'apppro-55d82.firebaseapp.com',
    storageBucket: 'apppro-55d82.firebasestorage.app',
    measurementId: 'G-H9XYR73264',
  );
}
